### ISSUE TITLE
how to plot more than 2 trees?

### ISSUE THREAD

**Issue by liamxg** [schlegelp/tanglegram#15]
Dear @schlegelp,

Could I know how to plot more than 2 trees?

**Comment by schlegelp** [comment]
Sorry, forgot to respond here. If you install the package straight from Github:

```bash 
pip3 install git+https://github.com/schlegelp/tanglegram@master
```

Then you can use the [`tanglegram_many`](https://github.com/schlegelp/tanglegram/blob/cb3a46ba1741693a466e4fedf29e055d50902077/tanglegram/tangle.py#L192C5-L192C20) function to plot as many tanglegram as you want

```python
>>> import tanglegram as tg 
>>> fig = tg.tanglegram_many((data1, data2, data3, data4))
```

Please see the function's docstring for details.
