### ISSUE TITLE
What clustering method is used to create the dendogram?

### ISSUE THREAD

**Issue by a-damC** [schlegelp/tanglegram#16]
Hello,

I am comparing R's dendextend to your version. (I'm having pip install issues (issue is the computer I need to use is very very old! Nothing to do with your software)). 
In the dendextend workflow you can specify the clustering method of the distance matrix using hclust:
e.g. (set of numbers -> turn into distance matrix -> cluster -> turn into dendogram)
```
dend <- c(1,2,3,5,10,20,100) %>% dist %>% hclust("ave") %>% as.dendrogram
dend <- c(1,2,3,5,10,20,100) %>% dist %>% hclust("single") %>% as.dendrogram
dend <- c(1,1,2,3,5,10,20,100) %>% dist %>% hclust("complete") %>% as.dendrogram
```

Looking at your code (tangle.py) I could see you call  `scipy.cluster.hierarchy.linkage`.
From the [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html#scipy.cluster.hierarchy.linkage) it appears to use the following as default:
`linkage(y, method='single', metric='euclidean', optimal_ordering=False)`

Would you be able to confirm that single linkage is used or is it something else?

Kind regards,
Adam

**Comment by schlegelp** [comment]
Hi! Yes, by default it uses single linkage. You can change that behaviour using the `link_kwargs` parameter of the in the tanglegram function. 

Also just to say that the version PyPI is by now 3 years behind what's on Github. I haven't gotten around bundling things up into a new release. In particular, I wanted to add a number of functions beyond just the tanglegram (i.e. something more like R's `dendextend`) but kinda ran out of steam.

**Comment by a-damC** [comment]
Thank you for the quick response and additional information.
Digging into this for a project has been very interesting.
The main calculation I use on the R version which I think is not available on your python version is the [cophenetic correlation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.cophenet.html#scipy.cluster.hierarchy.cophenet) as some of the tanglegrams can be v.large and hard to visualise any difference. This single value can be handy to detect if there are major differences between the clustering.
All the best for any future endeavours with this work and thank you again.
