### ISSUE TITLE
Are the dendrograms even correct?

### ISSUE THREAD

**Issue by JLiao980706** [schlegelp/tanglegram#2]
Matrix as a input to linkage function will make linkage think that you are passing observation value rather than distance value. A condensed matrix is required for linkage to represent distance value.

**Comment by schlegelp** [comment]
Oh shocks, you're right. I had the commit sitting locally but never pushed it. It's fixed now - including some bug other bug fixes and minor improvements. Let me know if that works for you.

**Comment by schlegelp** [comment]
This issue has been solved with cce81ac22b24225d0ebf6f75d4878c19aba1d8e7
