### ISSUE TITLE
Push to pypi?

### ISSUE THREAD

**Issue by taylorreiter** [schlegelp/tanglegram#4]
We are interested in using your tanglegram code as a dependency for our tool, [KEGGDecoder](https://github.com/bjtully/BioData/tree/master/KEGGDecoder) (binderized repo [here](https://github.com/rotheconrad/KEGGDecoder-binder), pull request to integrate tanglegram [here](https://github.com/bjtully/BioData/pull/15)). Would you be willing to make your package pip installable?

**Comment by schlegelp** [comment]
Done. `pip install tanglegram` should work now. Haven't done extensive testing - let me know if it works for you.

**Comment by taylorreiter** [comment]
Thank you!! it worked for me, I will let you know if we encounter any issues in the future.
